/*

  Project:       1Sheeld Library 
  File:          IncludedShieldsDefines.h
                 
  Version:       1.2

  Compiler:      Arduino avr-gcc 4.3.2

  Author:        Integreight
                 
  Date:          2014.9

*/

#define INCLUDE_KEYPAD_SHIELD
#define INCLUDE_GPS_SHIELD
#define INCLUDE_SLIDER_SHIELD
#define INCLUDE_PUSH_BUTTON_SHIELD
#define INCLUDE_TOGGLE_BUTTON_SHIELD
#define INCLUDE_GAMEPAD_SHIELD
#define INCLUDE_PROXIMITY_SENSOR_SHIELD
#define INCLUDE_MIC_SHIELD
#define INCLUDE_TEMPERATURE_SENSOR_SHIELD
#define INCLUDE_LIGHT_SENSOR_SHIELD
#define INCLUDE_PRESSURE_SENSOR_SHIELD
#define INCLUDE_GRAVITY_SENSOR_SHIELD
#define INCLUDE_ACCELEROMETER_SENSOR_SHIELD
#define INCLUDE_GYROSCOPE_SENSOR_SHIELD
#define INCLUDE_ORIENTATION_SENSOR_SHIELD
#define INCLUDE_MAGNETOMETER_SENSOR_SHIELD
#define INCLUDE_PHONE_SHIELD
#define INCLUDE_SMS_SHIELD
#define INCLUDE_CLOCK_SHIELD
#define INCLUDE_KEYBOARD_SHIELD
#define INCLUDE_TWITTER_SHIELD
#define INCLUDE_VOICE_RECOGNIZER_SHIELD
#define INCLUDE_TERMINAL_SHIELD
#define INCLUDE_FACEBOOK_SHIELD
#define INCLUDE_NOTIFICATION_SHIELD
#define INCLUDE_SEVEN_SEGMENT_SHIELD
#define INCLUDE_SKYPE_SHIELD
#define INCLUDE_MUSIC_PLAYER_SHIELD
#define INCLUDE_EMAIL_SHIELD
#define INCLUDE_FOURSQUARE_SHIELD
#define INCLUDE_CAMERA_SHIELD
#define INCLUDE_BUZZER_SHIELD
#define INCLUDE_LED_SHIELD
#define INCLUDE_LCD_SHIELD
#define INCLUDE_TEXT_TO_SPEECH_SHIELD
#define INCLUDE_DATA_LOGGER_SHIELD
#define INCLUDE_PATTERN_SHIELD
#define INCLUDE_INTERNET_SHIELD
#define INCLUDE_COLOR_DETECTOR_SHIELD
#define INCLUDE_NFC_SHIELD
#define INCLUDE_GLCD_SHIELD
#define INCLUDE_VIBRATION_SHIELD
#define INCLUDE_BARCODE_SCANNER_SHIELD
#define INCLUDE_FINGERPRINT_SCANNER_SHIELD
#define INCLUDE_FACE_DETECTOR_SHIELD
#define INCLUDE_CHART_SHIELD
#define INCLUDE_IOT_SHIELD
